// Generated by CoffeeScript 1.3.1
var ONE_YEAR, app, derby, express, expressApp, gzippo, http, path, publicPath, root, server, serverError;

http = require('http');

path = require('path');

express = require('express');

gzippo = require('gzippo');

derby = require('derby');

app = require('../app');

serverError = require('./serverError');

ONE_YEAR = 1000 * 60 * 60 * 24 * 365;

root = path.dirname(path.dirname(__dirname));

publicPath = path.join(root, 'public');

(expressApp = express()).use(express.favicon()).use(gzippo.staticGzip(publicPath, {
  maxAge: ONE_YEAR
})).use(express.compress()).use(express.bodyParser()).use(express.methodOverride()).use(app.router()).use(expressApp.router).use(serverError(root));

module.exports = server = http.createServer(expressApp);

expressApp.all('*', function(req) {
  throw "404: " + req.url;
});

derby.use('racer-db-mongo');

var store = app.createStore({
  listen: server
, db: {
		type: "Mongo"
	,	uri: 'mongodb://localhost/database'
	}
});

var model = store.createModel();

server.once('connection', function(){
	createAuction();
	setInterval(function(){
		declareResults();
		createAuction();
	}, 1000*5*60);
});

function createAuction(){
	//model.subscribe("auction", function(err, auction){
		model.set('auction.0.ending', new Date(new Date().getTime()+1000*0.5));
		//model.set('users.*.bid', 0);
		model.set('auction.0.xid', (Math.random()*10^10).toString(32));
		model.set('auction.0.winner', Math.random().toString(32));
	//});
}

function declareResults(){
	model.set('auction.0.ended', new Date());
	console.log('ENDING AUCTION');
}

