// Generated by CoffeeScript 1.3.1
var app, get, ready, render, sortableTable, _ref;

_ref = app = require('./index'), get = _ref.get, ready = _ref.ready;

render = require('./shared').render;



get('/:username', function(page, model, _arg) {
  var username = _arg.username;
  model.setNull('users.'+username, {name: username, createdat: new Date().getTime()});
  model.ref('_user', 'users.'+username);
  return render(page, 'bid');
});

ready(function(model) {
  var alpha, cols, rows;
  window.bid = function(){
    model.set('_user.bid', document.getElementById('bid').value);
  };

  model.set('_showReconnect', true);
  exports.connect = function() {
    model.set('_showReconnect', false);
    setTimeout((function() {
      return model.set('_showReconnect', true);
    }), 1000);
    return model.socket.socket.connect();
  };
  return exports.reload = function() {
    return window.location.reload();
  };
});
