// Generated by CoffeeScript 1.3.1
var app, get, ready, render, _ref;

_ref = app = require('derby').createApp(module), get = _ref.get, ready = _ref.ready;

render = require('./shared').render;

require('./home');
require('./bid');




app.post('/!#gotopage', function(page, model, _arg) {
    model.setNull('users.default', {name: 'default', createdat: new Date().getTime(), bid: 999999999999})
    var args, body, query;
    body = _arg.body, query = _arg.query;
    args = JSON.stringify({
      method: method,
      body: body,
      query: query
    }, null, '  ');
    var username = args.username;
    model.setNull('users.'+username, {name: username, createdat: new Date().getTime()});
    return page.redirect('/'+_arg.username);
  });




ready(function(model) {
  model.set('_showReconnect', true);
  exports.connect = function() {
    model.set('_showReconnect', false);
    setTimeout((function() {
      return model.set('_showReconnect', true);
    }), 1000);
    return model.socket.socket.connect();
  };
  return exports.reload = function() {
    return window.location.reload();
  };
});
