// Generated by CoffeeScript 1.3.1
var app, get, ready, render, _ref;

_ref = app = require('derby').createApp(module), get = _ref.get, ready = _ref.ready;

render = require('./shared').render;

require('./home');
require('./bid');


ready(function(model) {

  window.model=model; 
  model.set('_showReconnect', true);
  exports.connect = function() {
    model.set('_showReconnect', false);
    setTimeout((function() {
      return model.set('_showReconnect', true);
    }), 1000);
    return model.socket.socket.connect();
  };
  return exports.reload = function() {
    return window.location.reload();
  };
});

/*
* Creates and evaluates new auctions every 15 mins
*/


